name: CI

on:
  push:
    branches: [ main, develop, update-dependencies ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        run: npx eslint . --ext .ts,.js --format github

      - name: Check TypeScript compilation (advisory)
        run: npx tsc --noEmit --skipLibCheck || echo "TypeScript check failed but continuing..."
        continue-on-error: true

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build development
        run: yarn build:dev

      - name: Build production
        run: yarn build

      - name: Validate module.json
        run: npx @typhonjs-fvtt/validate-manifest module.json

      - name: Upload build artifacts
        if: matrix.node-version == '18'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 7

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run security audit
        run: yarn audit --level moderate

      - name: Check for outdated packages
        run: yarn outdated || true

  package-integrity:
    name: Package Integrity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Verify package integrity
        run: yarn install --check-files

      - name: Check package.json format
        run: npx prettier --check package.json

      - name: Verify lockfile is up to date
        run: |
          yarn install --frozen-lockfile
          git diff --exit-code yarn.lock